name: 'Auto Build & Deploy'

on:
  pull_request_target:
    branches:
      - 'release/*'

jobs:
  auto-build-and-deploy:
    runs-on: ubuntu-latest
    env:
      CSE_NPM_TOKEN: ${{secrets.CSE_NPM_TOKEN}}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.CSE_NPM_TOKEN}}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: dependencies-install
        run: yarn install
      - name: build package
        run: yarn build:package
      - run: git config --global user.email "leehyeokjae97@gmail.com"
      - run: git config --global user.name "HyeokjaeLee"
      - name: deploy package
        run: git pull && npm version patch && git push && yarn deploy:package
      - name: build storybook
        run: yarn build:storybook
      - name: deploy storybook
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.CSE_NPM_TOKEN}}
          publish_dir: ./dist/storybook
