name: 'Auto Build & Deploy'

on:
  push:
    branches:
      - 'release/*'

jobs:
  dependencies-install:
    if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    env:
      CSE_NPM_TOKEN: ${{secrets.CSE_NPM_TOKEN}}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.CSE_NPM_TOKEN}}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: dependencies-install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: build package
        run: yarn build:package
      - name: deploy package
        run: npm version patch && git push && yarn deploy:package
      - name: build storybook
        run: yarn build:storybook
